server.port: 8080
## 开启数据缓存
caching:
  enabled: true
spring:
  # database
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/simpleshop
    username: root
    password: csc1234
  # rabbit
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    publisher-confirm-type: correlated # if this configuration is turned on, the future message will be with correlation_id
    publisher-returns: true # The last line of the configuration is to enable the return of failure to send.
  # cache
  cache:
    type: ehcache
    ehcache:
      config: classpath:/ehcache.xml

# other services
resource.server:
  query-app:
#    host: http://query-app-svc:8081/api
    host: http://localhost:8081/api
  order-app:
#    host: http://order-app-svc:8083/api
    host: http://localhost:8081/api
  product-app:
    host: http://localhost:8081/api
#    host: http://product-app-svc:8082/api
