apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: app1
  name: app1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: app1
    spec:
      initContainers:
        - name: init-cont
          image: busybox
          command: ['sh','c','while ! nc -z mysqldb 3306; do sleep 1; done;']
      containers:
        - image: shannonhung/app1:1.0.0
          imagePullPolicy: IfNotPresent
          name: simpleshopmysql
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysqldb:3306/simpleshop
            - name: SPRING_DATASOURCE_PASSWORD
              value: csc1234
          resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: app1
  name: app1
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: app1
  type: LoadBalancer
status:
  loadBalancer: {}
