apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mysqldb
  name: mysqldb
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysqldb
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mysqldb
    spec:
      containers:
      - image: shichoc/mysqlshop:latest
        imagePullPolicy: IfNotPresent
        name: mysqlshop
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: passwd
        resources: {}
        livenessProbe:
          exec:
            command:["mysqladmin,ping"]
          initialDelaySeconds:30
          periodSeconds:10
          timeoutSeconds:5
        readlinessProbe:
          exec:
            command:["mysql",-h,"127.0.0.1","-uroot","-ppassew","-e","SELECT 1"]
          initialDelaySeconds:5
          periodSeconds:2
          timeoutSeconds:1
status: {}
