apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mysqldb
  name: mysqldb
  namespace: test
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: mysqldb
  type: ClusterIP
status:
  loadBalancer: {}
